### ISSUE TITLE
Problem with Python 3.11 and/or Glyphs 3234+

### ISSUE THREAD

**Issue by Mark2Mark** [harbortype/ShowSmoothNodeAngleAndProportion#13]
Related to this [forum post ](https://forum.glyphsapp.com/t/something-went-wrong-inside-python-code/28802/23)

We get the error message popping up in Glyphs:

|=============================================|
**Something went wrong inside python code**
*** -[__NSArray0 objectAtIndex:]: index 0 beyond
bounds for empty NSArray
|=============================================|

It could be related to the Glyphs python 3.11, as it did not happen a week before, when we still used version 3.9.
If you uninstall the Glyphs python from the Plugin Manager > Modules, it will fetch that same 3.11 version and after a restart of Glyphs likely cause this issue.

**Comment by florianpircher** [comment]
I believe this should be fixed with this PR:

https://github.com/harbortype/ShowSmoothNodeAngleAndProportion/pull/12

**Comment by harbortype** [comment]
@Mark2Mark I’ve just accepted the #12 PR and fixed another thing. Does the plugin work for you now?

**Comment by Mark2Mark** [comment]
Thanks a lot! We didn’t have the time to check before now, sorry for the waiting. It seems to be fixed. Many thanks, much appreciated 🙇
