### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by schriftgestalt** [harbortype/ShowSmoothNodeAngleAndProportion#16]
I got this from a user: 
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/plugins.py", line 1413, in raiseException_

 File "GlyphsApp/GlyphsApp/plugins.py", line 1241, in drawBackgroundWithOptions_

 File "plugin.py", line 422, in backgroundInViewCoords
   pos2 = offcurve.position
          ^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'position'

App:3.3-3324 Plugin:1.4.1-10 System:15.0.1
```
it seems that here:
```
prevNode, nextNode = self.getPrevNextNodes(path, nodeIndex)
offcurveNodes = [prevNode, nextNode]
```
Either prevNode or nextNode can be `None` when `node` is a start or end node on an open path.

```
for i, offcurve in enumerate(offcurveNodes):
```
this seems overkill to put two objects into a list to enumerate it.

**Comment by harbortype** [comment]
Thank you for letting me know. I have pushed the commit b6d8a85 that prevents this error. I had not taken into account that a **smooth node** may exist as the start or end node of an open path. This scenario was not caught by the checks on line [410](https://github.com/harbortype/ShowSmoothNodeAngleAndProportion/blob/b6d8a85f56b8e036ffbf865b017b92a20a8f7b43/Show%20Smooth%20Node%20Angle%20and%20Proportion.glyphsReporter/Contents/Resources/plugin.py#L410).

I have also removed a few `enumerate`s as they were not really needed indeed.
