### ISSUE TITLE
Show both percentages when only an offcurve point is selected

### ISSUE THREAD

**Issue by weiweihuanghuang** [harbortype/ShowSmoothNodeAngleAndProportion#2]
Currently when you select only a offcurve point only 1 side of the percentage shows up but I think it would be useful to show both sides – until the ratio can be shown.

**Comment by weiweihuanghuang** [comment]
I forked the plugin to show only the ratio 
https://github.com/weiweihuanghuang/ShowSmoothNodeAngleAndProportion/tree/master/images

**Comment by harbortype** [comment]
I believe showing the ratio should be presented as an option to the user, defaulting to percentage. While ratios could be considered more correct, I think percentages are naturally easier to understand. I’ll add this option to the plugin.

**Comment by harbortype** [comment]
Commit 08369b9 shows both percentages when an offcurve is selected. I’ll work on the ratio now.

**Comment by harbortype** [comment]
Commit d34bb92e33cd2fac1f075a6b5105450203cc3f1d adds the option to display proportion as a single ratio value.
