### ISSUE TITLE
Showing incompatibility even when the shapes are exactly the same?

### ISSUE THREAD

**Issue by weiweihuanghuang** [harbortype/ShowSmoothNodeAngleAndProportion#3]
<img width="373" alt="Screen Shot 2019-03-10 at 6 17 22 pm" src="https://user-images.githubusercontent.com/1271897/54081899-01a52680-4361-11e9-9501-20acb7397a6a.png">
[TEST.zip](https://github.com/harbortype/ShowSmoothNodeAngleAndProportion/files/2949178/TEST.zip)

This is quite strange, I copied the same shape to 3 masters and yet it still shows as being not compatible? any ideas @schriftgestalt

**Comment by weiweihuanghuang** [comment]
Another one where by my understanding of how this works it should not show as incompatible, it's the middle section of an s where there is a straight line:

[TEST2.zip](https://github.com/harbortype/ShowSmoothNodeAngleAndProportion/files/2949186/TEST2.zip)

Even when all the proportions are matched up, it still shows as having different proportion values:

Segment 1+2:
Light
<img width="591" alt="Screen Shot 2019-03-10 at 6 36 00 pm" src="https://user-images.githubusercontent.com/1271897/54082045-a4f73b00-4363-11e9-9020-a2748d32f8d7.png">
Regular
<img width="526" alt="Screen Shot 2019-03-10 at 6 36 03 pm" src="https://user-images.githubusercontent.com/1271897/54082047-aa548580-4363-11e9-833e-6fe40f4cfc61.png">
Bold
<img width="371" alt="Screen Shot 2019-03-10 at 6 36 05 pm" src="https://user-images.githubusercontent.com/1271897/54082048-ad4f7600-4363-11e9-9d12-f76abc2a9fe9.png">

Segment 2+3
Light:
<img width="306" alt="Screen Shot 2019-03-10 at 6 36 10 pm" src="https://user-images.githubusercontent.com/1271897/54082049-b3dded80-4363-11e9-87c9-8583d3286974.png">
Regular:
<img width="300" alt="Screen Shot 2019-03-10 at 6 36 13 pm" src="https://user-images.githubusercontent.com/1271897/54082051-b80a0b00-4363-11e9-9108-77b68c5393b6.png">
Bold:
<img width="257" alt="Screen Shot 2019-03-10 at 6 36 15 pm" src="https://user-images.githubusercontent.com/1271897/54082053-ba6c6500-4363-11e9-821e-59a9f53ebeab.png">

**Comment by harbortype** [comment]
There is a problem on line 42:

https://github.com/harbortype/ShowSmoothNodeAngleAndProportion/blob/cf7db9a4d003c77c7732c7c98b2d4630e10fe160/Show%20Smooth%20Node%20Angle%20and%20Proportion.glyphsReporter/Contents/Resources/plugin.py#L42-L43

`lyr.isMasterLayer` is returning all layers (including non-master layers), which I believe is a bug on Glyphs. I’ll take a better look at it tomorrow.

**Comment by schriftgestalt** [comment]
I had a look. I forgot that the `.isMasterLayer` is not in the wrapper, yet. I fixed it. But that is a problem here as it needs some special caseing in the plugin. For versions without the fix, you need to add parentheses (`.isMasterLayer()`), for the new version, you don’t. To avoid this, you can do: `lyr.layerId == lye.associatedMasterId`
