### ISSUE TITLE
Does not work in G3b

### ISSUE THREAD

**Issue by LibertyType** [harbortype/ShowSmoothNodeAngleAndProportion#6]
The _Show Smooth Node Angle and Proportion_ plugin does not work at all in G3b.

**Comment by harbortype** [comment]
I just pushed an update that fixes most of the issues on Glyphs 3. All basic functionality should work as expected. Please let me know if you find any other issues.

(The context menu is currently broken and I’ll take a look at it in the next couple of days.)
